dahao:
  version: 1.0.0
  schema_version: 1.0.0
  type: dao-constitution

organization:
  name: Example DAO
  established: 2025-01-22
  chain: ethereum
  multisig: "0x0000000000000000000000000000000000000000"

validation:
  strict_mode: true
  required_sections:
    - constitution
    - terms
    - governance
    - tokens
  
  file_patterns:
    constitution: "constitution/**/*.yaml"
    terms: "terms/**/*.yaml"
    governance: "governance/**/*.yaml"
    proposals: "proposals/**/*.yaml"
    
  schema_validation:
    enabled: true
    schemas:
      - https://dahao.org/schemas/v1/document-schema.yaml
      - https://dahao.org/schemas/v1/term-schema.yaml
      - https://dahao.org/schemas/v1/governance-schema.yaml
      - https://dahao.org/schemas/v1/member-schema.yaml
      - https://dahao.org/schemas/v1/proposal-schema.yaml

integrations:
  ipfs:
    enabled: true
    gateway: https://ipfs.io
    
  snapshot:
    enabled: true
    space: example-dao
    
  discord:
    enabled: true
    guild_id: "1234567890"
    
  github:
    enabled: true
    org: example-dao
    repo: governance

automation:
  proposal_sync: true
  member_sync: true
  vote_recording: true
  
ci_cd:
  validate_on_push: true
  auto_format: true
  spell_check: true
  
  deployment:
    branch: main
    ipfs_pin: true
    arweave_backup: false

metadata:
  maintainers:
    - governance-working-group
    - technical-committee
  contact: governance@exampledao.org
  documentation: https://docs.exampledao.org